    
            
   



    do case
       case v0=1 
         DO sav51 
       case v0=6
          DO dire
          DO firma
             ramka0.Visible =.F.
             ekran0.Show    

       case v0=7

      ENDCASE
      
      ****************    sav56   ******************************
      
                     PROCEDURE sav51
                     
                     
                     
      
         @ 15 ,50 say v0

         ? 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'
                           INKEY(0)
                     
                     
                     
                     RETURN
                     
         