
      rem   Posleden arhiv 07.03.2014
    *        pause
           CLS
           pause  EO16
      d:
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip eo16.zip d:\eo16
      cd d:\eo16
      c:\hlp\pk\pkunzip -o eo16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\SYNC\mink

           CLS
           pause    KO16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip ko16.zip d:\ko16\
      cd d:\ko16
      c:\hlp\pk\pkunzip -o ko16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\SYNC\mink


          CLS
          pause  RT16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip rt16.zip d:\rt16\
      cd d:\rt16
      c:\hlp\pk\pkunzip -o rt16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\SYNC\mink

         CLS
         pause   TO16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip to16.zip d:\to16\
      cd d:\to16
      c:\hlp\pk\pkunzip -o to16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\SYNC\mink

         CLS
         pause  EV16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip ev16.zip d:\ev16\
      cd d:\ev16
      c:\hlp\pk\pkunzip -o ev16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\SYNC\mink

         CLS
         pause   TN16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip tn16.zip d:\tn16\
      cd d:\tn16
      c:\hlp\pk\pkunzip -o tn16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\

           CLS
           pause   KA16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip ka16.zip d:\ka16\
      cd d:\ka16
      c:\hlp\pk\pkunzip -o ka16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\

           CLS
           pause   AP16
      cls
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip ap16.zip d:\ap16\
      cd d:\ap16
      c:\hlp\pk\pkunzip -o ap16.zip
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
      cd d:\


           CLS
           pause   M216
      cls
      c:
      c:\hlp\pk\pkunzip -o d:\SYNC\arhi\home_16.zip m216.zip c:\m216\
      cd c:\m216
      c:\hlp\pk\pkunzip -o m216.zip c:\m216\
      copy C:\HLP\podred\podred.mem
      c:\hlp\podred\podred.exe
  *   cd d:\

    *       CLS
    *      pause   SE16
    * cls
    * c:\hlp\pk\pkunzip -o d:\SYNC\arhi\mink_16.zip se16.zip d:\se16\
    * cd d:\se16
    * c:\hlp\pk\pkunzip -o se16.zip
    * copy C:\HLP\podred\podred.mem
    * c:\hlp\podred\podred.exe
      cd d:\



      rem View   4Ed       €  • ˆ ‚ ˆ  €
      rem   C:\HLP\PK\PKZIP -vm chef_14
      rem   pause
      rem   pkzip -d chef_14.zip ho14.zip
      rem   C:\HLP\PK\PKZIP -vm chef_14
      rem   pause
      rem   pkzip -a chef_14.zip ho14.zip
      rem   C:\HLP\PK\PKZIP -vm chef_14
      rem   pause





      REM    ¨§²°¨¢ /¤®¡ ¢¿  ´ ©«
      rem    pkzip -d chef_11.zip ho11.zip
      rem    pkzip -a chef_11.zip ho11.zip

      REM    ¤®¡ ¢¿ ´ ¨«
      rem    \hlp\pkzip % -  %

      REM    € „ˆ‘Š…’€
      REM    \hlp\pkzip a:\arh -&v \hotel\*.*

      REM    ‚‘ˆ—Šˆ ”€‰‹‚… € „ˆ…Š’ˆŸ’€
      rem    \hlp\pkzip nc  *.*


      REM    „„ˆ…Š’ˆˆ ˆ ”€‰‹‚…’ ‚ ’Ÿ•
      REM    pkzip -pr dnev07 *.*


      REM               € ‡ €  • ˆ ‚ ˆ  €

      REM    ’ „ˆ‘Š…’€
      REM    \hlp\pk\pkunzip -o a:\arh d:\install\novfax

      REM    ‚‘ˆ—Šˆ ”€‰‹‚… € „ˆ…Š’ˆŸ’€
      REM    \hlp\pk\pkunzip -o arh


      REM    „„ˆ…Š’ˆˆ ˆ ”€‰‹‚…’ ‚ ’Ÿ• ‚ ’…Š“™€’€ „ˆ…Š’ˆŸ
      REM    \hlp\pk\pkunzip -d dnev07
