   @ echo off
   @ mode con cols=20 lines=5 
   @ rem balcon -n /?  > aaa.txt
   @ "D:\Program Files\Balcon\balcon" -c -s -2 -v 70 -n Microsoft Anna
 
   @ rem balcon -f "VOICE.txt" -w "book.wav" 
   @ rem balcon -n Irina -t "Tuday you are on dentist at 16o'clock" -s -5 -v 70
   @ rem balcon -t "Hi Chefo " -s -2 -v 70
   @ rem balcon -t "Tuday you are on dentist at 16o'clock" -s -2 -v 70 -n "Irina" 
   @ rem balcon -n "Irina" -t "Днес си на зъболекар" --encoding "unicode" -id 1026 -s -2 -v 70 


 
