  @ echo off 
  @ start notepad
  @  if exist M:\__KOSI_C80\NUL (echo M:\__KOSI_C80 | C:\HLP\EXE\clip.exe
          C:\HLP\VBS\CLIP.VBS)
  @  if exist O:\__KOSI_C100\NUL (echo O:\__KOSI_C100 | C:\HLP\EXE\clip.exe
          C:\HLP\VBS\CLIP.VBS)

  @  if exist C:\__PETQ-C\NUL ( echo C:\__PETQ-C | C:\HLP\EXE\clip.exe
                              C:\HLP\VBS\CLIP.VBS)
  @  if exist D:\__PETQ-D\NUL ( echo D:\__PETQ-D | C:\HLP\EXE\clip.exe
             C:\HLP\VBS\CLIP.VBS)

  


