rem @  copy \hlp\pr.bat \hlp\greshka
CLS
ECHO       ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออื
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                      € ……H ”€… !!!                   ว
ECHO       ว                                                                  ว
ECHO       ว               ‘…H…’… ‘…’€’€  ’…’… –…“€’€ !        ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ว                                                                  ว
ECHO       ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออุ
pause>NUL
