   mode con cols=80 lines=10    

      REM TASKKILL /? |MORE
      REM PAUSE 
      
      rem  TASKKILL /F /IM MpCmdRun.exe /IM MpCmdRun.exe

      rem    pause
      rem  EXIT 

      rem  WmiPrvSE.exe

      REM START \HLP\JOB\PROCEXP.EXE

7z.exe
      TASKKILL /F /IM 7z.exe
      TASKKILL /F /IM AbbyyNewsReader.exe  
      TASKKILL /F /IM AEADISRV.EXE  
      TASKKILL /F /IM armsvc.exe 
      TASKKILL /F /IM ApplicationFrameHost.exe /IM  ApplicationFrameHost.exe
      TASKKILL /F /IM Ati2evxx.exe /IM  Ati2evxx.exe
 REM     TASKKILL /F /IM audiodg.exe /IM audiodg.exe
      TASKKILL /F /IM BCompare.exe /IM BCompare.exe
      TASKKILL /F /IM backgroundTaskHost.exe /IM backgroundTaskHost.exe
      TASKKILL /F /IM chrome.EXE   /IM chrome.EXE
REM   TASKKILL /F /IM conhost.exe /IM conhost.exe NIKOGA
      TASKKILL /F /IM dasHost.exe   /IM dasHost.exe
      TASKKILL /F /IM CvtCtrlSpl54.dll /IM CvtCtrlSpl54.dll
      TASKKILL /F /IM csrss.exe /IM csrss.exe
      TASKKILL /F /IM dllhost.exe /IM dllhost.exe
      TASKKILL /F /IM dwm.exe  /IM dwm.exe
      TASKKILL /F /IM fontdrvhost.exe  /IM fontdrvhost.exe
      TASKKILL /F /IM FlashUtil_ActiveX.exe  /IM FlashUtil_ActiveX.exe
      TASKKILL /F /IM FlightSettings.dll /IM FlightSettings.dll
      TASKKILL /F /IM FileSyncShell.dll /IM FileSyncShell.dll
      TASKKILL /F /IM fontdrvhost.exe /IM fontdrvhost.exe
      TASKKILL /F /IM HelpPane.exe /IM HelpPane.exe
      TASKKILL /F /IM IExplore.exe /IM IExplore.exe

      TASKKILL /F /IM InstallAgent.exe/IM InstallAgent.exe
      TASKKILL /F /IM LockApp.exe /IM  LockApp.exe
      TASKKILL /F /IM MagicPlus_helper.exe /IM MagicPlus_helper.exe

      TASKKILL /F /IM MicrosoftEdge.exe /IM MicrosoftEdge.exe
      TASKKILL /F /IM MicrosoftEdgeCP.exe /IM MicrosoftEdgeCP.exe

      TASKKILL /F /IM MpCmdRun.exe 
      TASKKILL /F /IM MSASCui.exe /IM  MSASCui.exe
    
      TASKKILL /F /IM mode.com /IM mode.com
REM  spira DOS     NetworkUXBroker.exe
      TASKKILL /F /IM ntvdm.exe /IM ntvdm.exe
      TASKKILL /F /IM NisSrv.exe /IM NisSrv.exe
      TASKKILL /F /IM OneDriveSetup.exe /IM OneDriveSetup.exe
      TASKKILL /F /IM rundll32.exe

      TASKKILL /F /IM RuntimeBroker.exe   /IM RuntimeBroker.exe 
      TASKKILL /F /IM SearchIndexer.exe   /IM SearchIndexer.exe
      TASKKILL /F /IM sc.exe  /IM sc.exe
      TASKKILL /F /IM SearchProtocolHost.exe  
      TASKKILL /F /IM SettingSyncHost.exe 
      TASKKILL /F /IM ShellExperienceHost.exe   /IM ShellExperienceHost.exe
      TASKKILL /F /IM splwow64.exe   /IM Ssplwow64.exe
REM   TASKKILL /F /IM sihost.exe   /IM sihost.exe  NIKOGA
rem      TASKKILL /F /IM svchost.exe   /IM svchost.exe 

      TASKKILL /F /IM subst.exe /IM subst.exe
      TASKKILL /F /IM sync-taskbar.exe /IM sync-taskbar.exe
      TASKKILL /F /IM sync-worker.exe /IM sync-worker.exe
      TASKKILL /F /IM taskhostw.exe       /IM taskhostw.exe
      TASKKILL /F /IM TeamViewer.exe      /IM TeamViewer.exe
      TASKKILL /F /IM tv_w32.exe          /IM tv_w32.exe
      TASKKILL /F /IM TeamViewer_Service.exe /IM TeamViewer_Service.exe
      TASKKILL /F /IM unsecapp.exe /IM unsecapp.exe
      TASKKILL /F /IM wininit.exe /IM wininit.exe
      TASKKILL /F /IM WerFault.exe
      TASKKILL /F /IM winlogon.exe /IM winlogon.exe
      TASKKILL /F /IM WmiPrvSE.exe /IM WmiPrvSE.exe
      TASKKILL /F /IM wmpnetwk.exe /IM wmpnetwk.exe
      TASKKILL /F /IM wscript.exe  /IM wscript.exe 
      TASKKILL /F /IM WUDFHost.exe /IM WUDFHost.exe
      TASKKILL /F /IM wuapihost.exe /IM wuapihost.exe
      TASKKILL /F /IM zvprtsrv.exe /IM zvprtsrv.exe

WerFault.exe

rem   pause  



