   mode con cols=80 lines=10    

      REM TASKKILL /? |MORE
      REM PAUSE 
      
      rem butldsk.sys
      SCHTASKS /Delete           /TN User_Feed_Synchronization-{FC880777-87F2-44EB-B95E-AEE26A35DD93} /F

    TASKKILL /F /IM svchost.exe	


      rem  WmiPrvSE.exe

      REM START \HLP\JOB\PROCEXP.EXE
      TASKKILL /F /IM 7z.exe
      TASKKILL /F /IM AbbyyNewsReader.exe 
      TASKKILL /F /IM AcroRd32.exe 
      TASKKILL /F /IM armsvc.exe
      TASKKILL /F /IM AEADISRV.EXE  
      TASKKILL /F /IM armsvc.exe 
      TASKKILL /F /IM ApplicationFrameHost.exe /IM  ApplicationFrameHost.exe
      TASKKILL /F /IM Ati2evxx.exe /IM  Ati2evxx.exe
 REM  TASKKILL /F /IM audiodg.exe /IM audiodg.exe
      TASKKILL /F /IM BCompare.exe /IM BCompare.exe
      TASKKILL /F /IM Bluefish.exe /IM Bluefish.exe
      TASKKILL /F /IM backgroundTaskHost.exe /IM backgroundTaskHost.exe
      TASKKILL /F /IM _chrome.EXE   /IM chrome.EXE
  REM    TASKKILL /F /IM chrome.EXE   /IM chrome.EXE
      TASKKILL /F /IM conhost.exe /IM conhost.exe          // nai- dolu
      TASKKILL /F /IM dasHost.exe   /IM dasHost.exe
      TASKKILL /F /IM dwm.exe
      TASKKILL /F /IM CvtCtrlSpl54.dll /IM CvtCtrlSpl54.dll
      TASKKILL /F /IM csrss.exe /IM csrss.exe
      TASKKILL /F /IM dllhost.exe /IM dllhost.exe
      TASKKILL /F /IM dwm.exe  /IM dwm.exe 
      TASKKILL /F /IM msedge.exe
      TASKKILL /F /IM fontdrvhost.exe  /IM fontdrvhost.exe
      TASKKILL /F /IM FlashUtil_ActiveX.exe  /IM FlashUtil_ActiveX.exe
      TASKKILL /F /IM FlightSettings.dll /IM FlightSettings.dll
      TASKKILL /F /IM FileSyncShell.dll 
      TASKKILL /F /IM fontdrvhost.exe 
      TASKKILL /F /IM Frameless.exe
      TASKKILL /F /IM Frameless.exe
      TASKKILL /F /IM Frameless.exe
      TASKKILL /F /IM hamachi-2-ui.exe
      TASKKILL /F /IM hamachi-2.exe
      rem TASKKILL /F /IM IExplore.exe
      TASKKILL /F /IM jp2launcher.exe
      TASKKILL /F /IM Microsoft.ZuneVideo_3.6.10811.0_x86__8wekyb3d8bbwe
      TASKKILL /F /IM Microsoft.Windows.Photos_15.618.18170.0_x86__8wekyb3d8bbwe
      TASKKILL /F /IM microsoft.windowscommunicationsapps_17.6568.46361.0_x86__8wekyb3d8bbwe
      TASKKILL /F /IM HelpPane.exe 
      TASKKILL /F /IM InstallAgent.exe
      TASKKILL /F /IM LockApp.exe 
      TASKKILL /F /IM hamachi-2.exe
      TASKKILL /F /IM LMIGuardianSvc.exe 
      TASKKILL /F /IM MagicPlus.exe
      TASKKILL /F /IM MagicPlus_helper.exe
      TASKKILL /F /IM  Microsoft.BingWeather_4.3.193.0_x86__8wekyb3d8bbw
      TASKKILL /F /IM MicrosoftEdge.exe 
      TASKKILL /F /IM MicrosoftEdgeCP.exe 
      TASKKILL /F /IM MpCmdRun.exe 
      TASKKILL /F /IM MSASCui.exe 
      TASKKILL /F /IM mode.com 
REM  spira DOS     NetworkUXBroker.exe
      TASKKILL /F /IM ntvdm.exe 
      TASKKILL /F /IM NisSrv.exe 
      TASKKILL /F /IM OneDriveSetup.exe 
      TASKKILL /F /IM plugin_host.exe
      TASKKILL /F /IM rundll32.exe 
      TASKKILL /F /IM RuntimeBroker.exe    
      TASKKILL /F /IM SearchIndexer.exe   
      TASKKILL /F /IM sc.exe  /IM sc.exe
      TASKKILL /F /IM SearchProtocolHost.exe  
      TASKKILL /F /IM SettingSyncHost.exe 
      TASKKILL /F /IM ShellExperienceHost.exe 
      TASKKILL /F /IM sedsvc.exe
      TASKKILL /F /IM SnapTimer.exe
      TASKKILL /F /IM splwow64.exe
REM   TASKKILL /F /IM sihost.exe   /IM sihost.exe  NIKOGA
      TASKKILL /F /IM subst.exe 
      TASKKILL /F /IM sync-taskbar.exe 
      TASKKILL /F /IM sync-worker.exe 
      TASKKILL /F /IM SnapTimer.exe
      TASKKILL /F /IM taskhostw.exe       
      TASKKILL /F /IM TeamViewer_Service.exe 
      TASKKILL /F /IM Timeout.exe     
      TASKKILL /F /IM tv_w32.exe         
      TASKKILL /F /IM tvnviewer.exe
      TASKKILL /F /IM tvnserver.exe
      TASKKILL /F /IM unsecapp.exe 
      TASKKILL /F /IM UPDA_K.EXE
      TASKKILL /F /IM xmrig.exe 
      TASKKILL /F /IM wininit.exe 
      TASKKILL /F /IM WerFault.exe
      TASKKILL /F /IM winlogon.exe 
      TASKKILL /F /IM WmiPrvSE.exe 
      TASKKILL /F /IM wmpnetwk.exe 
      TASKKILL /F /IM WINWORD.EXE
      TASKKILL /F /IM wscript.exe  
      TASKKILL /F /IM WUDFHost.exe 
      TASKKILL /F /IM wuapihost.exe 
      TASKKILL /F /IM zvprtsrv.exe    
      TASKKILL /F /IM conhost.exe  
      TASKKILL /F /IM conhost.exe
      TASKKILL /F /IM conhost.exe
      TASKKILL /F /IM conhost.exe
      TASKKILL /F /IM conhost.exe  
      TASKKILL /F /IM dllhost.exe
      TASKKILL /F /IM sihost.exe
      TASKKILL /F /IM cmd.exe     
      TASKKILL /F /IM RuntimeBroker.exe
      TASKKILL /F /IM SkypeBackgroundHost
      TASKKILL /F /IM SkypeApp
      TASKKILL /F /IM InputApp_cw5n1h2txyewy 
      TASKKILL /F /IM RuntimeBroker 
      TASKKILL /F /IM YourPhone
      TASKKILL /F /IM Microsoft.Windows.Cortana_cw5n1h2txyewy
      TASKKILL /F /IM dllhost.exe     
      TASKKILL /F /IM VMonitor.exe
      TASKKILL /F /IM SystemSettings.exe
      TASKKILL /F /IM svchost.exe 
      TASKKILL /F /IM svchost.exe 
      TASKKILL /F /IM AEADISRV.EXE
      TASKKILL /F /IM MsMpEng.exe
      TASKKILL /F /IM hamachi-2.exe
      TASKKILL /F /IM StartMenuExperienceHost.exe
      TASKKILL /F /IM WinStore.App.exe
      TASKKILL /F /IM smartscreen.exe
      TASKKILL /F /IM Viber.exe


rem cmd.exe
rem   pause  



