   mode con cols=80 lines=10    

      REM TASKKILL /? |MORE
      REM TASKKILL /F /IM AbbyyNewsReader.exe
      REM PAUSE 
      
      rem butldsk.sys
      SCHTASKS /Delete           /TN User_Feed_Synchronization-{FC880777-87F2-44EB-B95E-AEE26A35DD93} /F

    wmic process where name='svchost.exe' delete


      rem  WmiPrvSE.exe

      REM START \HLP\JOB\PROCEXP.EXE
      wmic process where name='7z.exe' delete
      wmic process where name='AbbyyNewsReader.exe' delete
      wmic process where name='AcroRd32.exe' delete
      wmic process where name='armsvc.exe' delete
      wmic process where name='AEADISRV.EXE' delete
      wmic process where name='armsvc.exe' delete
      wmic process where name='ApplicationFrameHost.exe' delete
      wmic process where name='Ati2evxx.exe' delete
 REM  wmic process where name='audiodg.exe /IM audiodg.exe
      wmic process where name='BCompare.exe' delete
      wmic process where name='Bluefish.exe
      wmic process where name='backgroundTaskHost.exe' delete
      wmic process where name='_chrome.EXE' delete
  REM    wmic process where name='chrome.EXE   /IM chrome.EXE
      wmic process where name='conhost.exe' delete
      wmic process where name='dasHost.exe' delete
      wmic process where name='dwm.exe' delete
      wmic process where name='CvtCtrlSpl54.dll' delete
      wmic process where name='csrss.exe' delete
      wmic process where name='dllhost.exe' delete
      wmic process where name='dwm.exe' delete 
      wmic process where name='msedge.exe' delete
      wmic process where name='fontdrvhost.exe' delete
      wmic process where name='FlashUtil_ActiveX.exe' delete
      wmic process where name='FlightSettings.dll' delete
      wmic process where name='FileSyncShell.dll' delete
      wmic process where name='fontdrvhost.exe' delete
      wmic process where name='Frameless.exe' delete
      wmic process where name='Frameless.exe' delete
      wmic process where name='Frameless.exe' delete
      wmic process where name='hamachi-2-ui.exe' delete
      wmic process where name='hamachi-2.exe' delete
      rem wmic process where name='IExplore.exe' delete
      wmic process where name='jp2launcher.exe' delete
      wmic process where name='Microsoft.ZuneVideo_3.6.10811.0_x86__8wekyb3d8bbwe' delete
      wmic process where name='Microsoft.WindowsStore_2015.7.1.0_x86__8wekyb3d8bbwe' delete
      wmic process where name='Microsoft.Windows.Photos_15.618.18170.0_x86__8wekyb3d8bbwe' delete
      wmic process where name='microsoft.windowscommunicationsapps_17.6568.46361.0_x86__8wekyb3d8bbwe' delete
      wmic process where name='HelpPane.exe' delete
      wmic process where name='InstallAgent.exe' delete
      wmic process where name='LockApp.exe' delete
      wmic process where name='hamachi-2.exe' delete
      wmic process where name='LMIGuardianSvc.exe' delete
      wmic process where name='MagicPlus.exe' delete
      wmic process where name='MagicPlus_helper.exe' delete
      wmic process where name=' Microsoft.BingWeather_4.3.193.0_x86__8wekyb3d8bbw' delete
      wmic process where name='MicrosoftEdge.exe' delete
      wmic process where name='MicrosoftEdgeCP.exe' delete
      wmic process where name='MpCmdRun.exe 
      wmic process where name='MSASCui.exe 
      wmic process where name='mode.com' delete
REM  spira DOS     NetworkUXBroker.exe
      wmic process where name='ntvdm.exe' delete
      wmic process where name='NisSrv.exe' delete
      wmic process where name='OneDriveSetup.exe' delete
rem   wmic process where name='plugin_host.exe' delete
      wmic process where name='rundll32.exe' delete
      wmic process where name='RuntimeBroker.exe' delete 
      wmic process where name='SearchIndexer.exe' delete
      wmic process where name='sc.exe' delete
      wmic process where name='SearchProtocolHost.exe' delete
      wmic process where name='SettingSyncHost.exe' delete
      wmic process where name='ShellExperienceHost.exe' delete
      wmic process where name='sedsvc.exe' delete
      wmic process where name='SnapTimer.exe' delete
      wmic process where name='splwow64.exe' delete
REM   wmic process where name='sihost.exe   /IM sihost.exe  NIKOGA
      wmic process where name='subst.exe' delete
      wmic process where name='sync-taskbar.exe 
      wmic process where name='sync-worker.exe 
      wmic process where name='SnapTimer.exe
      wmic process where name='taskhostw.exe       
      wmic process where name='TeamViewer_Service.exe' delete 
      wmic process where name='Timeout.exe' delete
      wmic process where name='tv_w32.exe' delete
      wmic process where name='tvnviewer.exe' delete
      wmic process where name='tvnserver.exe' delete
      wmic process where name='unsecapp.exe' delete
      wmic process where name='UPDA_K.EXE' delete
      wmic process where name='xmrig.exe' delete
      wmic process where name='wininit.exe' delete
      wmic process where name='WerFault.exe' delete
      wmic process where name='winlogon.exe' delete
      wmic process where name='WmiPrvSE.exe' delete
      wmic process where name='wmpnetwk.exe' delete 
      wmic process where name='WINWORD.EXE' delete
      wmic process where name='wscript.exe' delete
      wmic process where name='WUDFHost.exe' delete
      wmic process where name='wuapihost.exe' delete
      wmic process where name='zvprtsrv.exe' delete
      wmic process where name='conhost.exe' delete
      wmic process where name='conhost.exe' delete
      wmic process where name='conhost.exe' delete
      wmic process where name='conhost.exe' delete
      wmic process where name='conhost.exe' delete
      wmic process where name='dllhost.exe' delete
   rem   wmic process where name='sihost.exe' delete
   rem   wmic process where name='cmd.exe' delete
      wmic process where name='RuntimeBroker.exe' delete
      wmic process where name='SkypeBackgroundHost' delete
      wmic process where name='SkypeApp' delete
      wmic process where name='InputApp_cw5n1h2txyewy' delete
      wmic process where name='RuntimeBroker' delete
      wmic process where name='YourPhone' delete
      wmic process where name='Microsoft.Windows.Cortana_cw5n1h2txyewy' delete
      wmic process where name='dllhost.exe' delete
      wmic process where name='VMonitor.exe' delete
      wmic process where name='SystemSettings.exe' delete
      wmic process where name='svchost.exe' delete
      wmic process where name='svchost.exe' delete
      wmic process where name='AEADISRV.EXE' delete
      wmic process where name='MsMpEng.exe
      wmic process where name='hamachi-2.exe' delete
      wmic process where name='StartMenuExperienceHost.exe' delete
      wmic process where name='WinStore.App.exe' delete
      wmic process where name='smartscreen.exe' delete
      wmic process where name='cmd.exe' delete
      wmic process where name='Editor.exe' delete

      echo bbbbbbbbbbbbbbbbbbbbb & pause


rem cmd.exe
rem   pause  



