[*]
[*] Motochopper: Android root exploit (Windows version)
[*] v1.0
[*] by Dan Rosenberg (@djrbliss)
[*]
[*] Tested on the Motorola Razr HD, Razr M, Razr Maxx HD, and Atrix HD.
[*] Supports lots of other devices as well. ;-)
[*]
[*] Before continuing, ensure that USB debugging is enabled, that you
[*] have the latest USB drivers installed, and that your phone
[*] is connected via USB.
[*]
[*] WARNING: This will likely void the warranty on your device. I am
[*] not responsible for any damage to your phone as a result using this
[*] tool.
[*]
[*] Press enter to root your phone...
Press any key to continue . . .
[*]
[*] Waiting for device...
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
[*] Device found.
[*] Pushing exploit...
cannot stat 'pwn': No such file or directory
Unable to chmod /data/local/tmp/pwn: No such file or directory
[*] Pushing root tools...
753 KB/s (91980 bytes in 0.119s)
764 KB/s (1867568 bytes in 2.386s)
419 KB/s (969701 bytes in 2.258s)
        pkg: /data/local/tmp/Superuser.apk
Failure [INSTALL_FAILED_ALREADY_EXISTS]
[*] Rooting phone...
/system/bin/sh: /data/local/tmp/pwn: not found
[*] Cleaning up...
rm failed for /data/local/tmp/pwn, No such file or directory
[*] Exploit complete. Press enter to reboot and exit.
Press any key to continue . . .













