REM @ echo off

 @     REM net use K: \\JULY\C /yes   
 @         net use K: \\7.180.153.35\c /YES       
      
 @      REM net use L: \\MAG1\C /yes  
 @      REM net use M: \\MAG2\C /yes   
 @      REM net use N: \\MAG3\C /yes   
 @      REM net use O: \\MAG4\C /yes 
 @          net use O: \\7.129.160.155\c /YES   
 @      REM net use P: \\MAG5\C /yes   
 @      REM net use Q: \\MAG5\C /yes 
 @      REM   @ net use Y: \\7.175.184.126\c /YES
    
 @      cls
 @      net view 
 @      net use
 @      PAUSE