@echo off
rem  reg add "HKCU\Software\Policies\Microsoft\Internet Explorer\Control Panel" /V HomePage 
   start   regedit.exe /S yourfile.reg   C:\DISC\HLP\EXE\FRAME\KILL\01.reg
 
pause

rem  'start /min reg export hklm\Software\King S0001.PRN'
REM  REG ADD /?
 
 rem   reg delete HKLM\Software\King 
 REM   REG DELETE HKLM\Software\King /Y
 REM       REG ADD HKLM\Software\King_A
 rem   start /min C:\DISC\HLP\EXE\FRAME\KILL\01.reg /silent
@echo off
reg add "HKCU\Software\Policies\Microsoft\Internet Explorer\Control Panel" /V HomePage 


  REM         start /min REG ADD HKLM\Software\King_A


 pause


 rem     REG ADD HKLM\Software\AADD
 rem     REG ADD HKEY_LOCAL_MACHINE\System\King
 REM     REG ADD HKEY_LOCAL_MACHINE\KingAcco
  REM       REG ADD HKLM\Software\King
 
   
 rem reg DELETE HKLM\Software\AADD

pause