 rem xcopy  C:\HLP\BAT\alen.bat "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp" /S /Y
 rem Instalira se sam ->  cv act sc interface RegisterTool.lnk   
 rem xcopy  "C:\HLP\EXE\Desktop Clock Plus-7\Desktop Clock Plus-7.exe" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp" /S /Y
 rem  xcopy  C:\HLP\BAT\DesktopS.bat "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp" /S /Y
 rem C:\Windows\explorer.exe "C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
 rem Instalira se sam -> Weather Clock

  re     xcopy  C:\DISC\HLP\BAT\StarUp_S.BAT "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp
        xcopy C:\DISC\HLP\VBS\StartUp.VBS  "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp" /S /Y
        C:\Windows\explorer.exe "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp"     