    @ECHO off


    START C:\HLP\LNK\iexplore.lnk http://weather.bg/0index.php?koiFail=RM5sea1&lng=0 
  REM  timeout 5 > NUL
    START C:\HLP\LNK\iexplore.lnk http://weather.bg/0index.php?koiFail=modelsWaves&lng=0#
 REM   timeout 5 > NUL
    START C:\HLP\LNK\iexplore.lnk  http://weather-webcam.eu/webcam-kamera-web-cam-from-lozenec-cherno-more-plaj-centralen
 REM   timeout 5 > NUL
    START C:\HLP\LNK\iexplore.lnk  http://asen.iliev.name/weather/java_script_stream.html
L
   

    
 
    