'' Set sapi=Createobject("sapi.spvoice")
MsgBox "COMPILE PROGRAM NOT START. PLEASE REMOVE FROM FOLDER HLP\ASCI FILES OPE.PRG  AND  OPEN1.PRG",16,"Greetings From JK" 
 
'' Set Zira = CreateObject("SAPI.spVoice")
'' Set Zira.Voice = Zira.GetVoices.Item(2)
'' Zira.Rate = 0
'' Zira.Volume = 100
'' Zira.Speak "COMPILE PROGRAM, NOT, START. PLEASE REMOVE FROM FOLDER HLP\ASCI, FILES,  OPEN, AND, OPEN1. "


