  
    COPY C:\%go%\godn.dbf      %dest%\ARHI
    COPY C:\%go%\mese.dbf      %dest%\ARHI
    COPY C:\%go%\spis.dbf      %dest%\ARHI
    COPY C:\%go%\dannom.mem    %dest%\ARHI
    COPY C:\%go%\harved.mem    %dest%\ARHI
    COPY C:\%go%\fdate.mem     %dest%\ARHI
    COPY C:\%go%\namhar.mem    %dest%\ARHI
    COPY C:\%go%\nulstoi.mem   %dest%\ARHI
    COPY C:\%go%\rabodni.mem   %dest%\ARHI
    COPY C:\%go%\inforuso.mem  %dest%\ARHI


