
C:\Windows\System32\wbem\wmic.exe process where name='VBoxTray.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='wscript.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='csrss.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='conhost.exe.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='dllhost.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='RuntimeBroker.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='svchost.exe' delete
C:\Windows\System32\wbem\wmic.exe process where name='fontdrvhost.exe' delete

C:\Windows\System32\wbem\wmic.exe process where name='wuapihost.exe' delete