

wmic process where name='ApplicationFrameHost.exe' delete
wmic process where name='CompPkgSrv.exe' delete
wmic process where name='csrss.exe' delete
wmic process where name='csrss.exe' delete
wmic process where name='dllhost.exe' delete
wmic process where name='GrooveMonitor.exe' delete
wmic process where name='HxTsr.exe' delete
wmic process where name='igfxEM.exe' delete
wmic process where name='MicrosoftWindows.Client.CBS_cw5n1h2txyewy' delete
wmic process where name='microsoft.windowscommunicationsapps_16005.14326.21798.0_x64__8wekyb3d8bbwe' delete 
wmic process where name='MicTray64.exe' delete
wmic process where name='RuntimeBroker.exe' delete 
wmic process where name='RuntimeBroker.exe' delete 
wmic process where name='RuntimeBroker.exe' delete  
wmic process where name='RuntimeBroker.exe' delete 
wmic process where name='RuntimeBroker.exe' delete 
wmic process where name='RuntimeBroker.exe' delete 
wmic process where name='smartscreen.exe' delete
wmic process where name='ShellExperienceHost.exe' delete
wmic process where name='SkypeBackgroundHost.exe' delete
wmic process where name='SkypeApp.exe' delete
wmic process where name='StartMenuExperienceHost.exe' delete
wmic process where name='svchost.exe' delete
wmic process where name='svchost.exe' delete
wmic process where name='svchost.exe' delete
rem wmic process where name='winlogon.exe' delete
wmic process where name='winlogon.exe' delete



